export const additionalProducts = [
  // CUTTING PRODUCTS
  {
    id: "9",
    name: "CLA (Conjugated Linoleic Acid)",
    price: 19.99,
    description:
      "CLA is a naturally occurring fatty acid that may help reduce body fat while preserving lean muscle mass. Each softgel contains 1000mg of high-quality CLA.",
    benefits: [
      "Supports fat loss while preserving lean muscle",
      "Helps improve body composition",
      "Supports metabolic health",
      "Derived from non-GMO safflower oil",
    ],
    ingredients: "Conjugated Linoleic Acid (from non-GMO Safflower Oil), Gelatin Softgel, Glycerin, Purified Water",
    directions: "Take 2 softgels twice daily with meals or as directed by your healthcare professional.",
    image: "/placeholder.svg?height=600&width=600",
    rating: 4.5,
    reviews: 78,
    stock: 65,
    featured: false,
    tags: ["cutting"],
  },
  {
    id: "10",
    name: "L-Carnitine Liquid",
    price: 27.99,
    description:
      "L-Carnitine helps transport fatty acids into the mitochondria where they can be burned for energy. This liquid formula provides 1100mg of L-Carnitine per serving for maximum absorption.",
    benefits: [
      "Supports fat metabolism and energy production",
      "Helps with exercise recovery",
      "Promotes endurance during workouts",
      "Great-tasting berry flavor",
    ],
    ingredients: "L-Carnitine L-Tartrate, Purified Water, Natural Berry Flavor, Citric Acid, Stevia Leaf Extract",
    directions:
      "Take 1 tablespoon (15ml) daily, preferably before exercise or as directed by your healthcare professional.",
    image: "/placeholder.svg?height=600&width=600",
    rating: 4.7,
    reviews: 92,
    stock: 50,
    featured: false,
    tags: ["cutting"],
  },
  {
    id: "11",
    name: "Green Tea Extract",
    price: 18.99,
    description:
      "Standardized to contain 50% EGCG, our Green Tea Extract supports metabolism and provides powerful antioxidant protection. Each capsule contains 500mg of green tea extract.",
    benefits: [
      "Supports healthy metabolism",
      "Provides antioxidant protection",
      "Promotes fat oxidation",
      "Supports overall wellness",
    ],
    ingredients: "Green Tea Leaf Extract (standardized to 50% EGCG), Vegetable Cellulose Capsule, Rice Flour",
    directions: "Take 1 capsule 1-2 times daily with food or as directed by your healthcare professional.",
    image: "/placeholder.svg?height=600&width=600",
    rating: 4.6,
    reviews: 85,
    stock: 70,
    featured: false,
    tags: ["cutting"],
  },
  {
    id: "12",
    name: "Garcinia Cambogia Extract",
    price: 21.99,
    description:
      "Standardized to contain 60% HCA (Hydroxycitric Acid), our Garcinia Cambogia Extract may help support appetite control and healthy weight management.",
    benefits: [
      "Supports appetite control",
      "Helps inhibit fat production",
      "Supports healthy serotonin levels",
      "Promotes healthy weight management",
    ],
    ingredients: "Garcinia Cambogia Extract (standardized to 60% HCA), Vegetable Cellulose Capsule, Rice Flour",
    directions:
      "Take 1 capsule 30 minutes before meals, three times daily, or as directed by your healthcare professional.",
    image: "/placeholder.svg?height=600&width=600",
    rating: 4.3,
    reviews: 67,
    stock: 55,
    featured: false,
    tags: ["cutting"],
  },
  {
    id: "13",
    name: "Chromium Picolinate",
    price: 14.99,
    description:
      "Chromium is an essential trace mineral that helps support healthy blood sugar levels and may assist with carbohydrate, protein, and fat metabolism.",
    benefits: [
      "Supports healthy glucose metabolism",
      "Helps maintain healthy blood sugar levels",
      "May help reduce carbohydrate cravings",
      "Supports macronutrient metabolism",
    ],
    ingredients:
      "Chromium Picolinate (providing 200mcg of elemental Chromium), Vegetable Cellulose Capsule, Rice Flour",
    directions: "Take 1 capsule daily with a meal or as directed by your healthcare professional.",
    image: "/placeholder.svg?height=600&width=600",
    rating: 4.4,
    reviews: 58,
    stock: 80,
    featured: false,
    tags: ["cutting"],
  },
  {
    id: "14",
    name: "Raspberry Ketones",
    price: 22.99,
    description:
      "Raspberry Ketones are natural compounds that give red raspberries their aroma. Our formula provides 500mg per capsule to support healthy metabolism and fat oxidation.",
    benefits: [
      "Supports fat breakdown",
      "Helps increase adiponectin levels",
      "Promotes healthy metabolism",
      "Supports weight management goals",
    ],
    ingredients: "Raspberry Ketones, Vegetable Cellulose Capsule, Rice Flour",
    directions: "Take 1 capsule twice daily with meals or as directed by your healthcare professional.",
    image: "/placeholder.svg?height=600&width=600",
    rating: 4.2,
    reviews: 63,
    stock: 45,
    featured: false,
    tags: ["cutting"],
  },
  {
    id: "15",
    name: "Forskolin Extract",
    price: 25.99,
    description:
      "Derived from the Coleus forskohlii plant, Forskolin may help support fat loss and preserve lean body mass. Each capsule contains 250mg of standardized extract.",
    benefits: [
      "Supports fat metabolism",
      "Helps preserve lean body mass",
      "Promotes cellular energy production",
      "Supports healthy testosterone levels",
    ],
    ingredients:
      "Coleus Forskohlii Root Extract (standardized to 10% Forskolin), Vegetable Cellulose Capsule, Rice Flour",
    directions: "Take 1 capsule twice daily with meals or as directed by your healthcare professional.",
    image: "/placeholder.svg?height=600&width=600",
    rating: 4.5,
    reviews: 72,
    stock: 60,
    featured: false,
    tags: ["cutting"],
  },
  {
    id: "16",
    name: "Apple Cider Vinegar Capsules",
    price: 16.99,
    description:
      "Get all the benefits of apple cider vinegar without the unpleasant taste. Each capsule contains 500mg of pure apple cider vinegar powder to support digestion and metabolism.",
    benefits: [
      "Supports healthy digestion",
      "Helps maintain healthy blood sugar levels",
      "Promotes feelings of fullness",
      "Convenient capsule form",
    ],
    ingredients: "Apple Cider Vinegar Powder, Vegetable Cellulose Capsule",
    directions: "Take 2 capsules daily with meals or as directed by your healthcare professional.",
    image: "/placeholder.svg?height=600&width=600",
    rating: 4.6,
    reviews: 89,
    stock: 75,
    featured: false,
    tags: ["cutting"],
  },
  {
    id: "17",
    name: "Caffeine + L-Theanine",
    price: 19.99,
    description:
      "Our balanced formula combines 100mg of caffeine with 200mg of L-Theanine to provide smooth, clean energy without the jitters or crash.",
    benefits: [
      "Provides sustained energy",
      "Enhances focus and alertness",
      "Promotes calm energy without jitters",
      "Supports cognitive function",
    ],
    ingredients: "Caffeine Anhydrous, L-Theanine, Vegetable Cellulose Capsule, Rice Flour",
    directions:
      "Take 1 capsule as needed, preferably in the morning or early afternoon. Do not exceed 3 capsules in 24 hours.",
    image: "/placeholder.svg?height=600&width=600",
    rating: 4.8,
    reviews: 112,
    stock: 90,
    featured: false,
    tags: ["cutting", "bulking"],
  },
  {
    id: "18",
    name: "Digestive Enzymes Complex",
    price: 23.99,
    description:
      "Our comprehensive blend of digestive enzymes helps break down proteins, fats, and carbohydrates for optimal nutrient absorption and digestive comfort.",
    benefits: [
      "Supports optimal digestion",
      "Helps reduce bloating and gas",
      "Enhances nutrient absorption",
      "Supports overall digestive health",
    ],
    ingredients: "Protease, Amylase, Lipase, Cellulase, Lactase, Bromelain, Papain, Vegetable Cellulose Capsule",
    directions: "Take 1 capsule with each meal or as directed by your healthcare professional.",
    image: "/placeholder.svg?height=600&width=600",
    rating: 4.7,
    reviews: 95,
    stock: 65,
    featured: false,
    tags: ["cutting", "bulking", "maintenance"],
  },

  // BULKING PRODUCTS
  {
    id: "19",
    name: "Creatine Monohydrate",
    price: 24.99,
    description:
      "Pharmaceutical grade creatine monohydrate to support muscle strength, power, and recovery. Each serving provides 5g of pure creatine monohydrate.",
    benefits: [
      "Increases strength and power output",
      "Supports muscle growth and recovery",
      "Enhances high-intensity exercise performance",
      "Promotes cellular hydration",
    ],
    ingredients: "100% Pure Micronized Creatine Monohydrate",
    directions:
      "Take one 5g scoop daily mixed with water or your favorite beverage. On training days, consume immediately after workout.",
    image: "/placeholder.svg?height=600&width=600",
    rating: 4.9,
    reviews: 145,
    stock: 100,
    featured: true,
    tags: ["bulking"],
  },
  {
    id: "20",
    name: "Beta-Alanine",
    price: 22.99,
    description:
      "Beta-Alanine helps buffer lactic acid buildup, allowing you to train harder and longer. Each serving provides 3.2g of pure beta-alanine.",
    benefits: [
      "Increases muscular endurance",
      "Delays muscle fatigue",
      "Supports high-intensity exercise performance",
      "Helps improve workout volume",
    ],
    ingredients: "100% Pure Beta-Alanine",
    directions:
      "Take one 3.2g scoop daily mixed with water or your favorite beverage. May be taken before or after workout.",
    image: "/placeholder.svg?height=600&width=600",
    rating: 4.7,
    reviews: 98,
    stock: 85,
    featured: false,
    tags: ["bulking"],
  },
  {
    id: "21",
    name: "L-Leucine Powder",
    price: 26.99,
    description:
      "L-Leucine is the primary branched-chain amino acid (BCAA) responsible for stimulating muscle protein synthesis. Each serving provides 5g of pure L-Leucine.",
    benefits: [
      "Stimulates muscle protein synthesis",
      "Supports muscle growth and recovery",
      "Helps prevent muscle breakdown",
      "Promotes anabolic environment",
    ],
    ingredients: "100% Pure L-Leucine",
    directions:
      "Take one 5g scoop 1-2 times daily, preferably before and/or after workout, mixed with water or your favorite beverage.",
    image: "/placeholder.svg?height=600&width=600",
    rating: 4.6,
    reviews: 87,
    stock: 70,
    featured: false,
    tags: ["bulking"],
  },
  {
    id: "22",
    name: "HMB (Beta-Hydroxy Beta-Methylbutyrate)",
    price: 34.99,
    description:
      "HMB is a metabolite of the amino acid leucine that helps prevent muscle protein breakdown and supports recovery. Each capsule provides 1000mg of HMB.",
    benefits: [
      "Reduces muscle protein breakdown",
      "Supports muscle recovery",
      "Helps preserve lean muscle mass",
      "May enhance strength gains",
    ],
    ingredients: "HMB (Beta-Hydroxy Beta-Methylbutyrate), Vegetable Cellulose Capsule, Rice Flour",
    directions: "Take 1 capsule 3 times daily, preferably with meals or as directed by your healthcare professional.",
    image: "/placeholder.svg?height=600&width=600",
    rating: 4.5,
    reviews: 76,
    stock: 60,
    featured: false,
    tags: ["bulking"],
  },
  {
    id: "23",
    name: "D-Aspartic Acid",
    price: 28.99,
    description:
      "D-Aspartic Acid is an amino acid that may help support natural testosterone production and hormone balance. Each serving provides 3g of D-Aspartic Acid.",
    benefits: [
      "Supports natural testosterone levels",
      "Promotes hormone balance",
      "May enhance strength and muscle gains",
      "Supports male reproductive health",
    ],
    ingredients: "D-Aspartic Acid",
    directions:
      "Take one 3g scoop daily, preferably in the morning with food. Cycle 8 weeks on, 4 weeks off, or as directed by your healthcare professional.",
    image: "/placeholder.svg?height=600&width=600",
    rating: 4.4,
    reviews: 68,
    stock: 55,
    featured: false,
    tags: ["bulking"],
  },
  {
    id: "24",
    name: "ZMA (Zinc Magnesium Aspartate)",
    price: 19.99,
    description:
      "ZMA is a synergistic combination of Zinc, Magnesium, and Vitamin B6 designed to support muscle recovery, sleep quality, and hormone production.",
    benefits: [
      "Supports muscle recovery and growth",
      "Promotes restful sleep",
      "Helps maintain healthy testosterone levels",
      "Supports immune function",
    ],
    ingredients:
      "Zinc (as Zinc Monomethionine), Magnesium (as Magnesium Aspartate), Vitamin B6 (as Pyridoxine HCl), Vegetable Cellulose Capsule",
    directions:
      "Take 3 capsules daily, preferably on an empty stomach 30-60 minutes before bedtime, or as directed by your healthcare professional.",
    image: "/placeholder.svg?height=600&width=600",
    rating: 4.7,
    reviews: 92,
    stock: 80,
    featured: false,
    tags: ["bulking", "maintenance"],
  },
  {
    id: "25",
    name: "Mass Gainer Digestive Enzymes",
    price: 27.99,
    description:
      "Specialized enzyme blend designed to help digest high-calorie meals and protein shakes, reducing bloating and discomfort while maximizing nutrient absorption.",
    benefits: [
      "Helps digest high-protein meals",
      "Reduces bloating and gas",
      "Enhances carbohydrate and fat digestion",
      "Maximizes nutrient absorption",
    ],
    ingredients: "Protease Blend, Amylase Blend, Lipase Blend, Lactase, Cellulase, Vegetable Cellulose Capsule",
    directions:
      "Take 2 capsules with high-calorie meals or protein shakes, or as directed by your healthcare professional.",
    image: "/placeholder.svg?height=600&width=600",
    rating: 4.6,
    reviews: 83,
    stock: 65,
    featured: false,
    tags: ["bulking"],
  },
  {
    id: "26",
    name: "Tribulus Terrestris",
    price: 23.99,
    description:
      "Standardized to contain 45% saponins, our Tribulus Terrestris extract may help support natural testosterone levels and male vitality.",
    benefits: [
      "Supports healthy testosterone levels",
      "Promotes male vitality and libido",
      "Supports muscle strength and recovery",
      "Enhances athletic performance",
    ],
    ingredients: "Tribulus Terrestris Extract (standardized to 45% saponins), Vegetable Cellulose Capsule, Rice Flour",
    directions: "Take 1 capsule 2-3 times daily with meals, or as directed by your healthcare professional.",
    image: "/placeholder.svg?height=600&width=600",
    rating: 4.3,
    reviews: 72,
    stock: 60,
    featured: false,
    tags: ["bulking"],
  },
  {
    id: "27",
    name: "Glutamine Powder",
    price: 21.99,
    description:
      "L-Glutamine is the most abundant amino acid in muscle tissue and plays a crucial role in recovery and immune function. Each serving provides 5g of pure L-Glutamine.",
    benefits: [
      "Supports muscle recovery",
      "Helps reduce muscle soreness",
      "Supports gut health and immune function",
      "Helps prevent muscle breakdown",
    ],
    ingredients: "100% Pure L-Glutamine",
    directions:
      "Take one 5g scoop 1-2 times daily, preferably post-workout and/or before bed, mixed with water or your favorite beverage.",
    image: "/placeholder.svg?height=600&width=600",
    rating: 4.8,
    reviews: 105,
    stock: 90,
    featured: false,
    tags: ["bulking", "cutting"],
  },
  {
    id: "28",
    name: "Vitamin D3 5000 IU",
    price: 18.99,
    description:
      "High-potency Vitamin D3 to support bone health, immune function, and muscle strength. Each softgel provides 5000 IU of Vitamin D3.",
    benefits: [
      "Supports bone health and density",
      "Enhances immune system function",
      "Promotes muscle strength and function",
      "Supports healthy testosterone levels",
    ],
    ingredients: "Vitamin D3 (as Cholecalciferol), Olive Oil, Gelatin Softgel, Glycerin",
    directions: "Take 1 softgel daily with a meal or as directed by your healthcare professional.",
    image: "/placeholder.svg?height=600&width=600",
    rating: 4.9,
    reviews: 118,
    stock: 100,
    featured: false,
    tags: ["bulking", "cutting", "maintenance"],
  },

  // MAINTENANCE/LEAN PRODUCTS
  {
    id: "29",
    name: "Multivitamin for Active Individuals",
    price: 29.99,
    description:
      "Comprehensive multivitamin formula specifically designed for active individuals to support overall health, energy production, and recovery.",
    benefits: [
      "Supports overall health and wellness",
      "Enhances energy production",
      "Promotes recovery from exercise",
      "Fills nutrient gaps in the diet",
    ],
    ingredients:
      "Vitamin A, C, D, E, K, B-Complex, Calcium, Magnesium, Zinc, Selenium, Iron, Iodine, Chromium, Biotin, and more",
    directions: "Take 2 capsules daily with food or as directed by your healthcare professional.",
    image: "/placeholder.svg?height=600&width=600",
    rating: 4.8,
    reviews: 132,
    stock: 95,
    featured: true,
    tags: ["maintenance", "cutting", "bulking"],
  },
  {
    id: "30",
    name: "Greens Superfood Powder",
    price: 39.99,
    description:
      "Nutrient-dense greens powder containing over 40 superfoods, antioxidants, and probiotics to support overall health, detoxification, and immune function.",
    benefits: [
      "Provides whole food nutrients",
      "Supports detoxification processes",
      "Enhances immune function",
      "Promotes alkaline balance",
    ],
    ingredients:
      "Organic Greens Blend (Spirulina, Chlorella, Wheatgrass, Barley Grass), Organic Vegetable Blend, Organic Berry Blend, Probiotic Blend, Digestive Enzyme Blend",
    directions:
      "Mix one scoop with 8-10 oz of water or your favorite beverage daily, or as directed by your healthcare professional.",
    image: "/placeholder.svg?height=600&width=600",
    rating: 4.7,
    reviews: 108,
    stock: 70,
    featured: true,
    tags: ["maintenance", "cutting"],
  },
  {
    id: "31",
    name: "Coenzyme Q10 (CoQ10)",
    price: 32.99,
    description:
      "CoQ10 is a powerful antioxidant that supports heart health, energy production, and exercise performance. Each softgel provides 200mg of CoQ10.",
    benefits: [
      "Supports cardiovascular health",
      "Enhances cellular energy production",
      "Provides antioxidant protection",
      "Supports exercise performance",
    ],
    ingredients: "Coenzyme Q10 (Ubiquinone), MCT Oil, Gelatin Softgel, Glycerin",
    directions:
      "Take 1 softgel daily with a meal containing fat for optimal absorption, or as directed by your healthcare professional.",
    image: "/placeholder.svg?height=600&width=600",
    rating: 4.6,
    reviews: 95,
    stock: 80,
    featured: false,
    tags: ["maintenance"],
  },
  {
    id: "32",
    name: "Adaptogen Complex",
    price: 34.99,
    description:
      "Comprehensive blend of adaptogenic herbs designed to help the body adapt to stress, support energy levels, and promote overall wellbeing.",
    benefits: [
      "Helps the body adapt to stress",
      "Supports healthy energy levels",
      "Promotes mental clarity and focus",
      "Supports immune function",
    ],
    ingredients:
      "Ashwagandha Root Extract, Rhodiola Rosea Extract, Holy Basil Leaf Extract, Eleuthero Root Extract, Schisandra Berry Extract, Vegetable Cellulose Capsule",
    directions: "Take 2 capsules daily with food or as directed by your healthcare professional.",
    image: "/placeholder.svg?height=600&width=600",
    rating: 4.7,
    reviews: 103,
    stock: 75,
    featured: false,
    tags: ["maintenance"],
  },
  {
    id: "33",
    name: "Joint Support Formula",
    price: 29.99,
    description:
      "Comprehensive formula designed to support joint health, mobility, and comfort for active individuals. Contains glucosamine, chondroitin, MSM, and more.",
    benefits: [
      "Supports joint structure and function",
      "Promotes joint mobility and flexibility",
      "Helps reduce exercise-induced discomfort",
      "Supports cartilage health",
    ],
    ingredients:
      "Glucosamine Sulfate, Chondroitin Sulfate, MSM (Methylsulfonylmethane), Boswellia Serrata Extract, Turmeric Extract, Hyaluronic Acid, Vegetable Cellulose Capsule",
    directions: "Take 3 capsules daily with food or as directed by your healthcare professional.",
    image: "/placeholder.svg?height=600&width=600",
    rating: 4.8,
    reviews: 115,
    stock: 85,
    featured: false,
    tags: ["maintenance", "bulking"],
  },
  {
    id: "34",
    name: "Electrolyte Complex",
    price: 24.99,
    description:
      "Complete electrolyte formula to support hydration, muscle function, and recovery. Sugar-free and perfect for active individuals.",
    benefits: [
      "Supports optimal hydration",
      "Prevents muscle cramps",
      "Enhances exercise performance",
      "Promotes faster recovery",
    ],
    ingredients:
      "Sodium, Potassium, Magnesium, Calcium, Chloride, Coconut Water Powder, Himalayan Pink Salt, Natural Flavors, Stevia Leaf Extract",
    directions:
      "Mix one scoop with 16-20 oz of water before, during, or after exercise, or as needed throughout the day.",
    image: "/placeholder.svg?height=600&width=600",
    rating: 4.9,
    reviews: 127,
    stock: 90,
    featured: false,
    tags: ["maintenance", "cutting", "bulking"],
  },
  {
    id: "35",
    name: "Omega-3-6-9 Complex",
    price: 26.99,
    description:
      "Balanced blend of essential fatty acids from fish oil, flaxseed oil, and borage oil to support heart health, brain function, and inflammation response.",
    benefits: [
      "Supports cardiovascular health",
      "Promotes brain function and cognitive health",
      "Helps maintain healthy inflammatory response",
      "Supports skin and joint health",
    ],
    ingredients:
      "Fish Oil Concentrate (providing EPA and DHA), Flaxseed Oil, Borage Oil, Gelatin Softgel, Glycerin, Purified Water",
    directions: "Take 2 softgels daily with food or as directed by your healthcare professional.",
    image: "/placeholder.svg?height=600&width=600",
    rating: 4.7,
    reviews: 98,
    stock: 85,
    featured: false,
    tags: ["maintenance"],
  },
  {
    id: "36",
    name: "Sleep Support Formula",
    price: 23.99,
    description:
      "Natural formula designed to promote relaxation, quality sleep, and recovery. Contains melatonin, GABA, L-Theanine, and herbal extracts.",
    benefits: [
      "Promotes relaxation and calmness",
      "Supports quality sleep",
      "Enhances recovery and regeneration",
      "Non-habit forming",
    ],
    ingredients:
      "Melatonin, GABA, L-Theanine, Valerian Root Extract, Passionflower Extract, Chamomile Extract, Magnesium Glycinate, Vegetable Cellulose Capsule",
    directions: "Take 1-2 capsules 30-60 minutes before bedtime, or as directed by your healthcare professional.",
    image: "/placeholder.svg?height=600&width=600",
    rating: 4.8,
    reviews: 112,
    stock: 80,
    featured: false,
    tags: ["maintenance", "cutting", "bulking"],
  },
  {
    id: "37",
    name: "Digestive Health Probiotic",
    price: 32.99,
    description:
      "Advanced probiotic formula with 50 billion CFU and 12 clinically studied strains to support gut health, immune function, and nutrient absorption.",
    benefits: [
      "Supports digestive health and function",
      "Helps maintain healthy gut microbiome",
      "Supports immune system function",
      "Promotes nutrient absorption",
    ],
    ingredients: "Probiotic Blend (12 strains, 50 billion CFU), Prebiotic Fiber Blend, Vegetable Cellulose Capsule",
    directions: "Take 1 capsule daily with or without food, or as directed by your healthcare professional.",
    image: "/placeholder.svg?height=600&width=600",
    rating: 4.9,
    reviews: 135,
    stock: 75,
    featured: false,
    tags: ["maintenance", "cutting", "bulking"],
  },
  {
    id: "38",
    name: "Antioxidant Complex",
    price: 28.99,
    description:
      "Powerful blend of antioxidants including Vitamin C, Vitamin E, Alpha Lipoic Acid, and more to support cellular health and combat oxidative stress.",
    benefits: [
      "Provides antioxidant protection",
      "Supports cellular health",
      "Helps combat exercise-induced oxidative stress",
      "Supports immune function",
    ],
    ingredients:
      "Vitamin C, Vitamin E, Alpha Lipoic Acid, Coenzyme Q10, Grape Seed Extract, Resveratrol, N-Acetyl Cysteine, Vegetable Cellulose Capsule",
    directions: "Take 2 capsules daily with food or as directed by your healthcare professional.",
    image: "/placeholder.svg?height=600&width=600",
    rating: 4.7,
    reviews: 94,
    stock: 70,
    featured: false,
    tags: ["maintenance"],
  },
]

